### ISSUE TITLE
3rd-party i18n launcher issue& mutil-account titile support 

### ISSUE THREAD

**Issue by Yomisana** [SN-Koarashi/XCoreNET#3]
- [x] launcher Sometime mojang since update i18n game file will let whole i18n only enginsh can used...so it mind be like when launch game will force verify i18n data file like overwrite? make sure game language stilll support :octocat: 
- [x] can have option support add player name in titile for launcher multi user?

**Comment by SN-Koarashi** [comment]
> * [ ]  launcher Sometime mojang since update i18n game file will let whole i18n only enginsh can used...so it mind be like when launch game will force verify i18n data file like overwrite? make sure game language stilll support :octocat:

okay

> * [ ]  can have option support add player name in titile for launcher multi user?

Which part are you referring to?
